-- MySQL Script generated by MySQL Workbench
-- Fri May 12 23:08:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projetfinal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projetfinal` ;

-- -----------------------------------------------------
-- Schema projetfinal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetfinal` DEFAULT CHARACTER SET utf8 ;
USE `projetfinal` ;

-- -----------------------------------------------------
-- Table `projetfinal`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetfinal`.`role` ;

CREATE TABLE IF NOT EXISTS `projetfinal`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `projetfinal`.`role` (`name` ASC);


-- -----------------------------------------------------
-- Table `projetfinal`.`promo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetfinal`.`promo` ;

CREATE TABLE IF NOT EXISTS `projetfinal`.`promo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `projetfinal`.`promo` (`name` ASC);


-- -----------------------------------------------------
-- Table `projetfinal`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetfinal`.`user` ;

CREATE TABLE IF NOT EXISTS `projetfinal`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pair_id` INT NULL,
  `role_id` INT NOT NULL,
  `promo_id` INT NULL,
  PRIMARY KEY (`id`, `role_id`),
  CONSTRAINT `fk_user_user`
    FOREIGN KEY (`pair_id`)
    REFERENCES `projetfinal`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `projetfinal`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_promo1`
    FOREIGN KEY (`promo_id`)
    REFERENCES `projetfinal`.`promo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `mailperso_UNIQUE` ON `projetfinal`.`user` (`email` ASC);

CREATE INDEX `fk_user_user_idx` ON `projetfinal`.`user` (`pair_id` ASC);

CREATE INDEX `fk_user_role1_idx` ON `projetfinal`.`user` (`role_id` ASC);

CREATE UNIQUE INDEX `pair_id_UNIQUE` ON `projetfinal`.`user` (`pair_id` ASC);

CREATE INDEX `fk_user_promo1_idx` ON `projetfinal`.`user` (`promo_id` ASC);


-- -----------------------------------------------------
-- Table `projetfinal`.`diary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetfinal`.`diary` ;

CREATE TABLE IF NOT EXISTS `projetfinal`.`diary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `introduction` LONGTEXT NOT NULL,
  `promo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `promo_id`),
  CONSTRAINT `fk_carnetdebord_promo1`
    FOREIGN KEY (`promo_id`)
    REFERENCES `projetfinal`.`promo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_carnetdebord_promo1_idx` ON `projetfinal`.`diary` (`promo_id` ASC);


-- -----------------------------------------------------
-- Table `projetfinal`.`conclusion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetfinal`.`conclusion` ;

CREATE TABLE IF NOT EXISTS `projetfinal`.`conclusion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NOT NULL,
  `diary_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `diary_id`, `user_id`),
  CONSTRAINT `fk_conclusion_carnetdebord1`
    FOREIGN KEY (`diary_id`)
    REFERENCES `projetfinal`.`diary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conclusion_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `projetfinal`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_conclusion_carnetdebord1_idx` ON `projetfinal`.`conclusion` (`diary_id` ASC);

CREATE INDEX `fk_conclusion_user1_idx` ON `projetfinal`.`conclusion` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `projetfinal`.`answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetfinal`.`answer` ;

CREATE TABLE IF NOT EXISTS `projetfinal`.`answer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` MEDIUMTEXT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  CONSTRAINT `fk_answer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `projetfinal`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_answer_user1_idx` ON `projetfinal`.`answer` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `projetfinal`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetfinal`.`question` ;

CREATE TABLE IF NOT EXISTS `projetfinal`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` MEDIUMTEXT NOT NULL,
  `diary_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  `answer_id` INT NULL,
  PRIMARY KEY (`id`, `diary_id`, `role_id`),
  CONSTRAINT `fk_question_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `projetfinal`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_carnetdebord1`
    FOREIGN KEY (`diary_id`)
    REFERENCES `projetfinal`.`diary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_answer1`
    FOREIGN KEY (`answer_id`)
    REFERENCES `projetfinal`.`answer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_question_role1_idx` ON `projetfinal`.`question` (`role_id` ASC);

CREATE INDEX `fk_question_carnetdebord1_idx` ON `projetfinal`.`question` (`diary_id` ASC);

CREATE INDEX `fk_question_answer1_idx` ON `projetfinal`.`question` (`answer_id` ASC);

CREATE UNIQUE INDEX `answer_id_UNIQUE` ON `projetfinal`.`question` (`answer_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
